CREATE TABLE IF NOT EXISTS equipment (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    equipment_code VARCHAR(50) NOT NULL UNIQUE,
    equipment_name VARCHAR(100),
    max_brackets INT DEFAULT NULL,
    allowed_models VARCHAR(1000) DEFAULT NULL,
    min_length DECIMAL(10,2) DEFAULT NULL,
    max_length DECIMAL(10,2) DEFAULT NULL,
    min_width DECIMAL(10,2) DEFAULT NULL,
    max_width DECIMAL(10,2) DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bracket (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    length_mm DECIMAL(10,2) NOT NULL,
    width_mm DECIMAL(10,2) NOT NULL,
    equipment_id BIGINT DEFAULT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
